export const data = [
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Gorgeous Plastic Chips",
    price: "744.00",
    count: "2",
    id: "1",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Refined Soft Mouse",
    price: "94.00",
    count: "3",
    id: "2",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Oriental Plastic Table",
    price: "373.00",
    count: "1",
    id: "3",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Gorgeous Concrete Salad",
    price: "283.00",
    count: "2",
    id: "4",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Practical Cotton Ball",
    price: "786.00",
    count: "6",
    id: "5",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Fantastic Granite Bike",
    price: "579.00",
    count: "2",
    id: "6",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Intelligent Wooden Soap",
    price: "750.00",
    count: "7",
    id: "7",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Incredible Soft Mouse",
    price: "704.00",
    count: "4",
    id: "8",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Intelligent Metal Mouse",
    price: "603.00",
    count: "7",
    id: "9",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Oriental Frozen Chicken",
    price: "4.00",
    count: "6",
    id: "10",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Bespoke Frozen Salad",
    price: "119.00",
    count: "3",
    id: "11",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Recycled Bronze Chair",
    price: "77.00",
    count: "5",
    id: "12",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Handmade Frozen Sausages",
    price: "753.00",
    count: "9",
    id: "13",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Modern Soft Chair",
    price: "337.00",
    count: "1",
    id: "14",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Generic Cotton Towels",
    price: "944.00",
    count: "2",
    id: "15",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Sleek Granite Soap",
    price: "621.00",
    count: "7",
    id: "16",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Small Granite Table",
    price: "504.00",
    count: "5",
    id: "17",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Intelligent Concrete Pizza",
    price: "925.00",
    count: "4",
    id: "18",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Licensed Wooden Computer",
    price: "11.00",
    count: "5",
    id: "19",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Intelligent Granite Computer",
    price: "226.00",
    count: "3",
    id: "20",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Luxurious Metal Chair",
    price: "975.00",
    count: "1",
    id: "21",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Electronic Frozen Ball",
    price: "642.00",
    count: "9",
    id: "22",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Rustic Fresh Mouse",
    price: "35.00",
    count: "4",
    id: "23",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Luxurious Wooden Ball",
    price: "22.00",
    count: "7",
    id: "24",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Electronic Wooden Gloves",
    price: "867.00",
    count: "8",
    id: "25",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Awesome Plastic Car",
    price: "626.00",
    count: "4",
    id: "26",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Oriental Concrete Chair",
    price: "996.00",
    count: "3",
    id: "27",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Elegant Fresh Chicken",
    price: "519.00",
    count: "6",
    id: "28",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Luxurious Metal Chicken",
    price: "368.00",
    count: "3",
    id: "29",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Tasty Granite Mouse",
    price: "649.00",
    count: "2",
    id: "30",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Electronic Soft Table",
    price: "672.00",
    count: "5",
    id: "31",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Intelligent Plastic Salad",
    price: "632.00",
    count: "1",
    id: "32",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Tasty Bronze Shirt",
    price: "296.00",
    count: "1",
    id: "33",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Ergonomic Metal Bike",
    price: "481.00",
    count: "8",
    id: "34",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Practical Granite Table",
    price: "440.00",
    count: "9",
    id: "35",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Unbranded Concrete Fish",
    price: "636.00",
    count: "3",
    id: "36",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Handcrafted Metal Shoes",
    price: "231.00",
    count: "6",
    id: "37",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Recycled Steel Cheese",
    price: "790.00",
    count: "2",
    id: "38",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Elegant Plastic Computer",
    price: "257.00",
    count: "1",
    id: "39",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Tasty Rubber Mouse",
    price: "274.00",
    count: "6",
    id: "40",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Fantastic Wooden Ball",
    price: "864.00",
    count: "7",
    id: "41",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Refined Bronze Pizza",
    price: "842.00",
    count: "5",
    id: "42",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Elegant Cotton Keyboard",
    price: "857.00",
    count: "1",
    id: "43",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Intelligent Frozen Tuna",
    price: "548.00",
    count: "5",
    id: "44",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Ergonomic Wooden Shirt",
    price: "713.00",
    count: "1",
    id: "45",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Awesome Fresh Tuna",
    price: "253.00",
    count: "2",
    id: "46",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Luxurious Soft Salad",
    price: "710.00",
    count: "7",
    id: "47",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Tasty Bronze Shoes",
    price: "896.00",
    count: "1",
    id: "48",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Oriental Concrete Pizza",
    price: "274.00",
    count: "4",
    id: "49",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Modern Metal Car",
    price: "174.00",
    count: "5",
    id: "50",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Bespoke Wooden Towels",
    price: "30.00",
    count: "5",
    id: "51",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Licensed Frozen Bacon",
    price: "714.00",
    count: "1",
    id: "52",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Recycled Concrete Shirt",
    price: "171.00",
    count: "2",
    id: "53",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Sleek Cotton Hat",
    price: "481.00",
    count: "7",
    id: "54",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Oriental Rubber Fish",
    price: "221.00",
    count: "5",
    id: "55",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Generic Concrete Shirt",
    price: "998.00",
    count: "7",
    id: "56",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Licensed Concrete Soap",
    price: "449.00",
    count: "5",
    id: "57",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Electronic Plastic Sausages",
    price: "523.00",
    count: "2",
    id: "58",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Handmade Fresh Ball",
    price: "708.00",
    count: "9",
    id: "59",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Rustic Granite Fish",
    price: "360.00",
    count: "6",
    id: "60",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Sleek Plastic Table",
    price: "379.00",
    count: "4",
    id: "61",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Awesome Steel Chicken",
    price: "143.00",
    count: "9",
    id: "62",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Recycled Fresh Bacon",
    price: "129.00",
    count: "4",
    id: "63",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Bespoke Granite Pants",
    price: "503.00",
    count: "5",
    id: "64",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Bespoke Rubber Chicken",
    price: "677.00",
    count: "5",
    id: "65",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Elegant Concrete Chair",
    price: "339.00",
    count: "7",
    id: "66",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Generic Plastic Mouse",
    price: "975.00",
    count: "8",
    id: "67",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Tasty Wooden Keyboard",
    price: "163.00",
    count: "6",
    id: "68",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Practical Cotton Pizza",
    price: "158.00",
    count: "7",
    id: "69",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Rustic Steel Shoes",
    price: "17.00",
    count: "7",
    id: "70",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Rustic Frozen Ball",
    price: "382.00",
    count: "7",
    id: "71",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Tasty Metal Bike",
    price: "305.00",
    count: "8",
    id: "72",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Generic Frozen Shoes",
    price: "231.00",
    count: "3",
    id: "73",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Incredible Cotton Chicken",
    price: "65.00",
    count: "4",
    id: "74",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Recycled Fresh Chicken",
    price: "313.00",
    count: "1",
    id: "75",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Sleek Wooden Fish",
    price: "406.00",
    count: "5",
    id: "76",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Licensed Bronze Sausages",
    price: "525.00",
    count: "8",
    id: "77",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Licensed Rubber Salad",
    price: "494.00",
    count: "3",
    id: "78",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Licensed Fresh Mouse",
    price: "601.00",
    count: "3",
    id: "79",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Oriental Concrete Chair",
    price: "167.00",
    count: "1",
    id: "80",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Small Plastic Mouse",
    price: "820.00",
    count: "7",
    id: "81",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Oriental Frozen Chicken",
    price: "904.00",
    count: "8",
    id: "82",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Handcrafted Bronze Computer",
    price: "755.00",
    count: "7",
    id: "83",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Electronic Fresh Sausages",
    price: "433.00",
    count: "5",
    id: "84",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Bespoke Soft Cheese",
    price: "419.00",
    count: "3",
    id: "85",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Fantastic Steel Hat",
    price: "339.00",
    count: "6",
    id: "86",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Fantastic Rubber Keyboard",
    price: "128.00",
    count: "1",
    id: "87",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Incredible Granite Computer",
    price: "1000.00",
    count: "1",
    id: "88",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Generic Wooden Soap",
    price: "426.00",
    count: "7",
    id: "89",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Refined Soft Computer",
    price: "881.00",
    count: "9",
    id: "90",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Electronic Plastic Tuna",
    price: "971.00",
    count: "5",
    id: "91",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Oriental Cotton Table",
    price: "571.00",
    count: "9",
    id: "92",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Tasty Fresh Ball",
    price: "805.00",
    count: "7",
    id: "93",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Luxurious Cotton Chips",
    price: "927.00",
    count: "6",
    id: "94",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Modern Rubber Cheese",
    price: "389.00",
    count: "7",
    id: "95",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Sleek Frozen Sausages",
    price: "783.00",
    count: "9",
    id: "96",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Refined Fresh Chair",
    price: "640.00",
    count: "3",
    id: "97",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Handcrafted Soft Keyboard",
    price: "881.00",
    count: "7",
    id: "98",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Unbranded Steel Chicken",
    price: "173.00",
    count: "1",
    id: "99",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Licensed Plastic Fish",
    price: "649.00",
    count: "6",
    id: "100",
  },
];
